### ISSUE TITLE
add Xd and exported files from the yesterday meeting

### ISSUE THREAD

**Issue by RizkiTH** [j-start/Sistem-Informasi-Akuntansi-Masjid_Desain#8]
hey guys, pls add the following files to the repository:
- [x] The Xd file
- [x] The Exported files

pls follow to place the specific file to **the right folder**, and pls rename those files to this following format:
1. For the Xd file, pls rename it to **date**`-yourXdFile.xd`
2. For the exported folder, pls rename it to **date**`-exported`

cheers,
Ryumada

**Comment by algorithmsevolve** [comment]
I have uploaded files that you have requested before. *Spelling Checked by @j-start/security
